### ISSUE TITLE
GitHub deprecation warnings.

### ISSUE THREAD

**Issue by danwdart** [LeapYear/github-rest#18]
My initialisatio code looks like:
```
let state = GitHubState {
          token = Just (AccessToken $ B.pack githubAccessToken)
        , userAgent = "x/y"
        , apiVersion = "v3"
    }
```

But when using it, GitHub emails me with:

```
[GitHub API] Deprecation notice for authentication via URL query parameters
<<snip>>
Please use the Authorization HTTP header instead, as using the `access_token` query parameter is deprecated. If this token is being used by an app you don't have control over, be aware that it may stop working as a result of this deprecation.
```

Guess the project is doing queries for the token and is suggested to otherwise move to auth headers?

I could have a look to see what could change...

Ta!

**Comment by brandon-leapyear** [comment]
Not sure what's going on here. The token is added with the `Authorization` header: https://github.com/LeapYear/github-rest/blob/master/src/GitHub/REST/Monad.hs#L95

Are you adding an `access_token` query parameter at the callsite? What does the callsite look like?

**Comment by danwdart** [comment]
Nope. Here's my code: https://github.com/danwdart/websites/blob/blog-comments/src/submit-comment.hs

**Comment by brandon-leapyear** [comment]
https://github.com/brandon-leapyear/github-rest-issue-18/commit/4cbc860327057c2f7778342a8bab48a1a4211c4d

I just ran your code and I'm not getting any deprecation emails. If you comment out the `runGitHubT` section, do you still get the deprecation email? (remember to change the user agent each time, since the email is sent out once every three days per token per user agent)

**Comment by brandon-leapyear** [comment]
Maybe this?
https://github.com/danwdart/websites/blob/423cca5bc381f877f96495c82d5f0951b3752aca/src/Html/Common/GitHub.hs#L128

**Comment by danwdart** [comment]
Hahaha, that'll be it, won't it... thanks!

**Comment by danwdart** [comment]
Aha, that'll be it.
So I guess I confused it with this because it's using the same token with two "apps". Thanks!
